kind: Template
apiVersion: v1
metadata:
  name: hibernator-roles
objects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: hibernation-curator
    rules:
    - apiGroups: ["hive.openshift.io"]
      resources: ["clusterdeployments"]
      verbs: ["get", "list", "patch"]
    - apiGroups: ["events.k8s.io"]
      resources: ["events"]
      verbs: ["create", "get", "update"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
        name: hibernation-curator
    subjects:
    - kind: ServiceAccount
      name: hibernator
      namespace: ${NAMESPACE}
    roleRef:
      kind: ClusterRole
      name: hibernation-curator
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: hibernator
      namespace: ${NAMESPACE}
parameters:
  - name: NAMESPACE 
    description: The namespace where the hibernate CronJobs were installed
    required: true